vpc_cidr                = "10.0.0.0/20"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones      = ["ap-south-1a", "ap-south-1b"]
private_ip_targets      = ["10.0.3.", "10.0.5."]
region_name             = "ap-south-1"
frontend_sg_prefix_name = "FrontendALBSG"
backend_sg_prefix_name  = "BackendALBSG"
app_frontend_sg         = "FrontendAppSG"
chatbot_frontend_alb    = "Chatbot23FrontendALB"
chatbot_backend_alb     = "Chatbot23BackendALB"
chatbot_frontend_tg     = "Chatbot23FrontendTG"
chatbot_backend_tg      = "Chatbot23BackendTG"
db_security_group       = "Chatbot23DBSecurityGroup"
nextauth_secret         = ""
db_url                  = ""
jwt_secret              = ""
jwt_secret_for_verify   = ""
openai_api_key          = ""
sender_password         = ""
access_key              = ""
secret_key              = ""
session_token           = ""
cluster_name            = "chatbot23-ecs-cluster"
repository_names        = ["chatbot23-frontend", "chatbot23-backend"]
codestart_connection    = "Chatbot23Connection"
frontend = {
  image  = "905418236735.dkr.ecr.ap-south-1.amazonaws.com/dev-chatbot23-frontend:latest"
  cpu    = 256
  memory = 512
  port   = 80
}
backend = {
  image  = "905418236735.dkr.ecr.ap-south-1.amazonaws.com/dev-chatbot23-backend:latest"
  cpu    = 256
  memory = 512
  port   = 80
}
pipeline_name                  = "Chatbot23BackendPipeline"
codebuild_project_name         = "CodeBuildBackendProj"
codebuild_fontend_project_name = "CodebuildFrontendProj"
frontend_pipeline_name         = "Chatbot23FrontendPipeline"
public_alb_ingress_ports       = ["80", "443"]
public_alb_egress_ports        = ["0"]
internal_alb_egress_ports      = ["0"]
internal_alb_ingress_ports     = ["8000"]
